### ISSUE TITLE
add or clarify license

### ISSUE THREAD

**Issue by slivingston** [chrisvxd/firestation#6]
Can you add more explicit indication of the license under which `firestation` is released? I found ["ISC" in package.json](https://github.com/chrisvxd/firestation/blob/08bdb12cdee7477525379c7aa6de8c601f818c67/package.json#L15), but I am not certain to what it refers. Is it https://opensource.org/licenses/ISC?

Some possibilities:
- add a file in the root of the sourcetree named LICENSE (or COPYING) that has a full copy of the license;
- add a description in the README along with a link to a full copy of the license (not necessarily in the repo);
- add copyright and license declarations in particular source code files.

This same issue applies to https://github.com/chrisvxd/firestation-demo

**Comment by chrisvxd** [comment]
@slivingston damn forgot I missed the license. Will add shortly. Thanks for noticing.

**Comment by slivingston** [comment]
Thanks for your work on `firestation`!

**Comment by chrisvxd** [comment]
@slivingston no worries. You got it up and running?

**Comment by chrisvxd** [comment]
Closed in 2348f0d
